### ISSUE TITLE
question

### ISSUE THREAD

**Issue by timchenxiaoyu** [bobrik/bay#2]
host1> docker run -d --net=host bobrik/bay-tracker \
  -listen 192.168.0.1:8888 -tracker 192.168.0.4:6881 -root /tmp

why  -tracker 192.168.0.4:6881  ? port =6881?

**Comment by bobrik** [comment]
This is an abandoned project, don't expect it to work 3 years after last commit.

**Comment by luisdavim** [comment]
it's a typo.
